// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        inStream_dout,
        inStream_empty_n,
        inStream_read,
        compressdStream_din,
        compressdStream_full_n,
        compressdStream_write,
        compressdStream_num_data_valid,
        compressdStream_fifo_cap,
        input_size,
        input_size_c2_din,
        input_size_c2_full_n,
        input_size_c2_write,
        input_size_c2_num_data_valid,
        input_size_c2_fifo_cap
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] inStream_dout;
input   inStream_empty_n;
output   inStream_read;
output  [31:0] compressdStream_din;
input   compressdStream_full_n;
output   compressdStream_write;
input  [31:0] compressdStream_num_data_valid;
input  [31:0] compressdStream_fifo_cap;
input  [31:0] input_size;
output  [31:0] input_size_c2_din;
input   input_size_c2_full_n;
output   input_size_c2_write;
input  [2:0] input_size_c2_num_data_valid;
input  [2:0] input_size_c2_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg inStream_read;
reg[31:0] compressdStream_din;
reg compressdStream_write;
reg input_size_c2_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    input_size_c2_blk_n;
reg   [31:0] input_size_read_reg_396;
reg    ap_block_state1;
wire   [0:0] icmp_ln63_fu_198_p2;
reg   [0:0] icmp_ln63_reg_491;
wire   [31:0] sub34_fu_258_p2;
reg   [31:0] sub34_reg_510;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln87_fu_264_p2;
reg   [0:0] icmp_ln87_reg_515;
wire   [7:0] select_ln80_fu_314_p3;
reg   [7:0] select_ln80_reg_524;
wire    ap_CS_fsm_state6;
wire   [7:0] select_ln80_1_fu_322_p3;
reg   [7:0] select_ln80_1_reg_529;
wire   [7:0] select_ln80_2_fu_330_p3;
reg   [7:0] select_ln80_2_reg_534;
wire   [7:0] select_ln80_3_fu_338_p3;
reg   [7:0] select_ln80_3_reg_539;
wire   [7:0] select_ln80_4_fu_346_p3;
reg   [7:0] select_ln80_4_reg_544;
reg   [10:0] dict_address0;
reg    dict_ce0;
reg    dict_we0;
reg   [431:0] dict_d0;
reg   [10:0] dict_address1;
reg    dict_ce1;
reg    dict_we1;
wire   [431:0] dict_q1;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_done;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_idle;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_ready;
wire   [10:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address0;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce0;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we0;
wire   [431:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d0;
wire   [10:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address1;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce1;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we1;
wire   [431:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d1;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_done;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_idle;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_ready;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_inStream_read;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_4_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_4_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_3_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_3_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_2_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_2_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_1_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_1_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx55_promoted157_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx55_promoted157_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx46_3_promoted155_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx46_3_promoted155_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx65_promoted153_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx65_promoted153_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx61_promoted151_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx61_promoted151_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx58_promoted149_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx58_promoted149_out_ap_vld;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_done;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_idle;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_ready;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_inStream_read;
wire   [31:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_din;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_write;
wire   [3:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid;
wire   [3:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap;
wire   [10:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address0;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce0;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_we0;
wire   [431:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_d0;
wire   [10:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address1;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce1;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_15_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_15_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_14_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_14_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_13_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_13_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_12_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_12_out_ap_vld;
wire   [7:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_11_out;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_11_out_ap_vld;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_done;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_idle;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_ready;
wire   [31:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_din;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_write;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_done;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_idle;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_ready;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_inStream_read;
wire   [31:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_din;
wire    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_write;
wire   [3:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid;
wire   [3:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap;
reg    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start_reg;
reg   [7:0] present_window_4_loc_fu_116;
reg   [7:0] present_window_3_loc_fu_112;
reg   [7:0] present_window_2_loc_fu_108;
reg   [7:0] present_window_1_loc_fu_104;
reg   [7:0] present_window_loc_fu_100;
reg   [7:0] arrayidx55_promoted157_loc_fu_96;
reg   [7:0] arrayidx46_3_promoted155_loc_fu_92;
reg   [7:0] arrayidx65_promoted153_loc_fu_88;
reg   [7:0] arrayidx61_promoted151_loc_fu_84;
reg   [7:0] arrayidx58_promoted149_loc_fu_80;
reg    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    ap_block_state9_on_subcall_done;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_block_state3_on_subcall_done;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire   [31:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap0;
wire   [31:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid0;
wire   [31:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap0;
wire   [31:0] grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start_reg = 1'b0;
#0 grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start_reg = 1'b0;
#0 grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start_reg = 1'b0;
#0 grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start_reg = 1'b0;
#0 grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start_reg = 1'b0;
end

lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_s_dict_RAM_T2P_BRAM_1R1W #(
    .DataWidth( 432 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
dict_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dict_address0),
    .ce0(dict_ce0),
    .we0(dict_we0),
    .d0(dict_d0),
    .address1(dict_address1),
    .ce1(dict_ce1),
    .we1(dict_we1),
    .d1(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d1),
    .q1(dict_q1)
);

lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start),
    .ap_done(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_done),
    .ap_idle(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_idle),
    .ap_ready(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_ready),
    .dict_address0(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address0),
    .dict_ce0(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce0),
    .dict_we0(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we0),
    .dict_d0(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d0),
    .dict_address1(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address1),
    .dict_ce1(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce1),
    .dict_we1(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we1),
    .dict_d1(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d1)
);

lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2 grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start),
    .ap_done(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_done),
    .ap_idle(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_idle),
    .ap_ready(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_ready),
    .inStream_dout(inStream_dout),
    .inStream_empty_n(inStream_empty_n),
    .inStream_read(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_inStream_read),
    .present_window_4_out(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_4_out),
    .present_window_4_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_4_out_ap_vld),
    .present_window_3_out(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_3_out),
    .present_window_3_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_3_out_ap_vld),
    .present_window_2_out(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_2_out),
    .present_window_2_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_2_out_ap_vld),
    .present_window_1_out(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_1_out),
    .present_window_1_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_1_out_ap_vld),
    .present_window_out(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_out),
    .present_window_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_out_ap_vld),
    .arrayidx55_promoted157_out(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx55_promoted157_out),
    .arrayidx55_promoted157_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx55_promoted157_out_ap_vld),
    .arrayidx46_3_promoted155_out(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx46_3_promoted155_out),
    .arrayidx46_3_promoted155_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx46_3_promoted155_out_ap_vld),
    .arrayidx65_promoted153_out(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx65_promoted153_out),
    .arrayidx65_promoted153_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx65_promoted153_out_ap_vld),
    .arrayidx61_promoted151_out(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx61_promoted151_out),
    .arrayidx61_promoted151_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx61_promoted151_out_ap_vld),
    .arrayidx58_promoted149_out(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx58_promoted149_out),
    .arrayidx58_promoted149_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx58_promoted149_out_ap_vld)
);

lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start),
    .ap_done(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_done),
    .ap_idle(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_idle),
    .ap_ready(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_ready),
    .inStream_dout(inStream_dout),
    .inStream_empty_n(inStream_empty_n),
    .inStream_read(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_inStream_read),
    .compressdStream_din(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_din),
    .compressdStream_full_n(compressdStream_full_n),
    .compressdStream_write(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_write),
    .compressdStream_num_data_valid(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid),
    .compressdStream_fifo_cap(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap),
    .arrayidx55_promoted157_reload(arrayidx55_promoted157_loc_fu_96),
    .arrayidx46_3_promoted155_reload(arrayidx46_3_promoted155_loc_fu_92),
    .arrayidx65_promoted153_reload(arrayidx65_promoted153_loc_fu_88),
    .arrayidx61_promoted151_reload(arrayidx61_promoted151_loc_fu_84),
    .arrayidx58_promoted149_reload(arrayidx58_promoted149_loc_fu_80),
    .sub34(sub34_reg_510),
    .dict_address0(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address0),
    .dict_ce0(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce0),
    .dict_we0(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_we0),
    .dict_d0(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_d0),
    .dict_address1(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address1),
    .dict_ce1(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce1),
    .dict_q1(dict_q1),
    .present_window_15_out(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_15_out),
    .present_window_15_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_15_out_ap_vld),
    .present_window_14_out(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_14_out),
    .present_window_14_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_14_out_ap_vld),
    .present_window_13_out(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_13_out),
    .present_window_13_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_13_out_ap_vld),
    .present_window_12_out(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_12_out),
    .present_window_12_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_12_out_ap_vld),
    .present_window_11_out(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_11_out),
    .present_window_11_out_ap_vld(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_11_out_ap_vld)
);

lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start),
    .ap_done(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_done),
    .ap_idle(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_idle),
    .ap_ready(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_ready),
    .compressdStream_din(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_din),
    .compressdStream_full_n(compressdStream_full_n),
    .compressdStream_write(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_write),
    .compressdStream_num_data_valid(compressdStream_num_data_valid),
    .compressdStream_fifo_cap(compressdStream_fifo_cap),
    .select_ln80_4(select_ln80_4_reg_544),
    .select_ln80_3(select_ln80_3_reg_539),
    .select_ln80_2(select_ln80_2_reg_534),
    .select_ln80_1(select_ln80_1_reg_529),
    .select_ln80(select_ln80_reg_524)
);

lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start),
    .ap_done(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_done),
    .ap_idle(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_idle),
    .ap_ready(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_ready),
    .inStream_dout(inStream_dout),
    .inStream_empty_n(inStream_empty_n),
    .inStream_read(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_inStream_read),
    .compressdStream_din(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_din),
    .compressdStream_full_n(compressdStream_full_n),
    .compressdStream_write(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_write),
    .compressdStream_num_data_valid(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid),
    .compressdStream_fifo_cap(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start_reg <= 1'b1;
        end else if ((grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_ready == 1'b1)) begin
            grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start_reg <= 1'b1;
        end else if ((grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_ready == 1'b1)) begin
            grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start_reg <= 1'b1;
        end else if ((grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_ready == 1'b1)) begin
            grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start_reg <= 1'b1;
        end else if ((grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_ready == 1'b1)) begin
            grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start_reg <= 1'b1;
        end else if ((grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_ready == 1'b1)) begin
            grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx46_3_promoted155_out_ap_vld == 1'b1))) begin
        arrayidx46_3_promoted155_loc_fu_92 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx46_3_promoted155_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx55_promoted157_out_ap_vld == 1'b1))) begin
        arrayidx55_promoted157_loc_fu_96 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx55_promoted157_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx58_promoted149_out_ap_vld == 1'b1))) begin
        arrayidx58_promoted149_loc_fu_80 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx58_promoted149_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx61_promoted151_out_ap_vld == 1'b1))) begin
        arrayidx61_promoted151_loc_fu_84 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx61_promoted151_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx65_promoted153_out_ap_vld == 1'b1))) begin
        arrayidx65_promoted153_loc_fu_88 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx65_promoted153_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln63_reg_491 <= icmp_ln63_fu_198_p2;
        input_size_read_reg_396 <= input_size;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln87_reg_515 <= icmp_ln87_fu_264_p2;
        sub34_reg_510 <= sub34_fu_258_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_1_out_ap_vld == 1'b1))) begin
        present_window_1_loc_fu_104 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_2_out_ap_vld == 1'b1))) begin
        present_window_2_loc_fu_108 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_3_out_ap_vld == 1'b1))) begin
        present_window_3_loc_fu_112 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_4_out_ap_vld == 1'b1))) begin
        present_window_4_loc_fu_116 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_4_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_out_ap_vld == 1'b1))) begin
        present_window_loc_fu_100 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        select_ln80_1_reg_529 <= select_ln80_1_fu_322_p3;
        select_ln80_2_reg_534 <= select_ln80_2_fu_330_p3;
        select_ln80_3_reg_539 <= select_ln80_3_fu_338_p3;
        select_ln80_4_reg_544 <= select_ln80_4_fu_346_p3;
        select_ln80_reg_524 <= select_ln80_fu_314_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state9_on_subcall_done)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln63_reg_491 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        compressdStream_din = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_din;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        compressdStream_din = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_din;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        compressdStream_din = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_din;
    end else begin
        compressdStream_din = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_din;
    end
end

always @ (*) begin
    if (((icmp_ln63_reg_491 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        compressdStream_write = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_write;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        compressdStream_write = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_write;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        compressdStream_write = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_write;
    end else begin
        compressdStream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dict_address0 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dict_address0 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address0;
    end else begin
        dict_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dict_address1 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dict_address1 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address1;
    end else begin
        dict_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dict_ce0 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dict_ce0 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce0;
    end else begin
        dict_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dict_ce1 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dict_ce1 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce1;
    end else begin
        dict_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dict_d0 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dict_d0 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d0;
    end else begin
        dict_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dict_we0 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dict_we0 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we0;
    end else begin
        dict_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        dict_we1 = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we1;
    end else begin
        dict_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln63_reg_491 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        inStream_read = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_inStream_read;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        inStream_read = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_inStream_read;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        inStream_read = grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_inStream_read;
    end else begin
        inStream_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        input_size_c2_blk_n = input_size_c2_full_n;
    end else begin
        input_size_c2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        input_size_c2_write = 1'b1;
    end else begin
        input_size_c2_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln63_fu_198_p2 == 1'd1) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((icmp_ln63_fu_198_p2 == 1'd0) & (1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((input_size_c2_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_done == 1'b0) | (grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state9_on_subcall_done = ((icmp_ln63_reg_491 == 1'd0) & (grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_done == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start = grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start_reg;

assign grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start_reg;

assign grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start_reg;

assign grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap0;

assign grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap0 = {{28{1'b0}}, {compressdStream_fifo_cap[3:0]}};

assign grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid0;

assign grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid0 = {{28{1'b0}}, {compressdStream_num_data_valid[3:0]}};

assign grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start_reg;

assign grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start_reg;

assign grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap0;

assign grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap0 = {{28{1'b0}}, {compressdStream_fifo_cap[3:0]}};

assign grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid = grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid0;

assign grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid0 = {{28{1'b0}}, {compressdStream_num_data_valid[3:0]}};

assign icmp_ln63_fu_198_p2 = ((input_size == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_264_p2 = ((sub34_fu_258_p2 > 32'd5) ? 1'b1 : 1'b0);

assign input_size_c2_din = input_size;

assign select_ln80_1_fu_322_p3 = ((icmp_ln87_reg_515[0:0] == 1'b1) ? grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_14_out : present_window_3_loc_fu_112);

assign select_ln80_2_fu_330_p3 = ((icmp_ln87_reg_515[0:0] == 1'b1) ? grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_13_out : present_window_2_loc_fu_108);

assign select_ln80_3_fu_338_p3 = ((icmp_ln87_reg_515[0:0] == 1'b1) ? grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_12_out : present_window_1_loc_fu_104);

assign select_ln80_4_fu_346_p3 = ((icmp_ln87_reg_515[0:0] == 1'b1) ? grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_11_out : present_window_loc_fu_100);

assign select_ln80_fu_314_p3 = ((icmp_ln87_reg_515[0:0] == 1'b1) ? grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_15_out : present_window_4_loc_fu_116);

assign start_out = real_start;

assign sub34_fu_258_p2 = ($signed(input_size_read_reg_396) + $signed(32'd4294967232));

endmodule //lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_s
