-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    inStream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inStream_empty_n : IN STD_LOGIC;
    inStream_read : OUT STD_LOGIC;
    compressdStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    compressdStream_full_n : IN STD_LOGIC;
    compressdStream_write : OUT STD_LOGIC;
    compressdStream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    compressdStream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    input_size : IN STD_LOGIC_VECTOR (31 downto 0);
    input_size_c2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    input_size_c2_full_n : IN STD_LOGIC;
    input_size_c2_write : OUT STD_LOGIC;
    input_size_c2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    input_size_c2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_FFFFFFC0 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal input_size_c2_blk_n : STD_LOGIC;
    signal input_size_read_reg_396 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal icmp_ln63_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln63_reg_491 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub34_fu_258_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub34_reg_510 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln87_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_reg_515 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln80_fu_314_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln80_reg_524 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal select_ln80_1_fu_322_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln80_1_reg_529 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln80_2_fu_330_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln80_2_reg_534 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln80_3_fu_338_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln80_3_reg_539 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln80_4_fu_346_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln80_4_reg_544 : STD_LOGIC_VECTOR (7 downto 0);
    signal dict_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal dict_ce0 : STD_LOGIC;
    signal dict_we0 : STD_LOGIC;
    signal dict_d0 : STD_LOGIC_VECTOR (431 downto 0);
    signal dict_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal dict_ce1 : STD_LOGIC;
    signal dict_we1 : STD_LOGIC;
    signal dict_q1 : STD_LOGIC_VECTOR (431 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_done : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_idle : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_ready : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce0 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we0 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d0 : STD_LOGIC_VECTOR (431 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d1 : STD_LOGIC_VECTOR (431 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_done : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_idle : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_ready : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_inStream_read : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_4_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_4_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_3_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_3_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_2_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_2_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_1_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx55_promoted157_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx55_promoted157_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx46_3_promoted155_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx46_3_promoted155_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx65_promoted153_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx65_promoted153_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx61_promoted151_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx61_promoted151_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx58_promoted149_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx58_promoted149_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_done : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_idle : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_ready : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_inStream_read : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_write : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce0 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_we0 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_d0 : STD_LOGIC_VECTOR (431 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_15_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_15_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_14_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_14_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_13_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_13_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_12_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_12_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_11_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_11_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_done : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_idle : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_ready : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_write : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_done : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_idle : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_ready : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_inStream_read : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_write : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start_reg : STD_LOGIC := '0';
    signal present_window_4_loc_fu_116 : STD_LOGIC_VECTOR (7 downto 0);
    signal present_window_3_loc_fu_112 : STD_LOGIC_VECTOR (7 downto 0);
    signal present_window_2_loc_fu_108 : STD_LOGIC_VECTOR (7 downto 0);
    signal present_window_1_loc_fu_104 : STD_LOGIC_VECTOR (7 downto 0);
    signal present_window_loc_fu_100 : STD_LOGIC_VECTOR (7 downto 0);
    signal arrayidx55_promoted157_loc_fu_96 : STD_LOGIC_VECTOR (7 downto 0);
    signal arrayidx46_3_promoted155_loc_fu_92 : STD_LOGIC_VECTOR (7 downto 0);
    signal arrayidx65_promoted153_loc_fu_88 : STD_LOGIC_VECTOR (7 downto 0);
    signal arrayidx61_promoted151_loc_fu_84 : STD_LOGIC_VECTOR (7 downto 0);
    signal arrayidx58_promoted149_loc_fu_80 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_block_state9_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        dict_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        dict_ce0 : OUT STD_LOGIC;
        dict_we0 : OUT STD_LOGIC;
        dict_d0 : OUT STD_LOGIC_VECTOR (431 downto 0);
        dict_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        dict_ce1 : OUT STD_LOGIC;
        dict_we1 : OUT STD_LOGIC;
        dict_d1 : OUT STD_LOGIC_VECTOR (431 downto 0) );
    end component;


    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inStream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inStream_empty_n : IN STD_LOGIC;
        inStream_read : OUT STD_LOGIC;
        present_window_4_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_4_out_ap_vld : OUT STD_LOGIC;
        present_window_3_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_3_out_ap_vld : OUT STD_LOGIC;
        present_window_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_2_out_ap_vld : OUT STD_LOGIC;
        present_window_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_1_out_ap_vld : OUT STD_LOGIC;
        present_window_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_out_ap_vld : OUT STD_LOGIC;
        arrayidx55_promoted157_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        arrayidx55_promoted157_out_ap_vld : OUT STD_LOGIC;
        arrayidx46_3_promoted155_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        arrayidx46_3_promoted155_out_ap_vld : OUT STD_LOGIC;
        arrayidx65_promoted153_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        arrayidx65_promoted153_out_ap_vld : OUT STD_LOGIC;
        arrayidx61_promoted151_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        arrayidx61_promoted151_out_ap_vld : OUT STD_LOGIC;
        arrayidx58_promoted149_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        arrayidx58_promoted149_out_ap_vld : OUT STD_LOGIC );
    end component;


    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inStream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inStream_empty_n : IN STD_LOGIC;
        inStream_read : OUT STD_LOGIC;
        compressdStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        compressdStream_full_n : IN STD_LOGIC;
        compressdStream_write : OUT STD_LOGIC;
        compressdStream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        compressdStream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        arrayidx55_promoted157_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        arrayidx46_3_promoted155_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        arrayidx65_promoted153_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        arrayidx61_promoted151_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        arrayidx58_promoted149_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        sub34 : IN STD_LOGIC_VECTOR (31 downto 0);
        dict_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        dict_ce0 : OUT STD_LOGIC;
        dict_we0 : OUT STD_LOGIC;
        dict_d0 : OUT STD_LOGIC_VECTOR (431 downto 0);
        dict_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        dict_ce1 : OUT STD_LOGIC;
        dict_q1 : IN STD_LOGIC_VECTOR (431 downto 0);
        present_window_15_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_15_out_ap_vld : OUT STD_LOGIC;
        present_window_14_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_14_out_ap_vld : OUT STD_LOGIC;
        present_window_13_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_13_out_ap_vld : OUT STD_LOGIC;
        present_window_12_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_12_out_ap_vld : OUT STD_LOGIC;
        present_window_11_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_11_out_ap_vld : OUT STD_LOGIC );
    end component;


    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        compressdStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        compressdStream_full_n : IN STD_LOGIC;
        compressdStream_write : OUT STD_LOGIC;
        compressdStream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        compressdStream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        select_ln80_4 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln80_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln80_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln80_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln80 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inStream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inStream_empty_n : IN STD_LOGIC;
        inStream_read : OUT STD_LOGIC;
        compressdStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        compressdStream_full_n : IN STD_LOGIC;
        compressdStream_write : OUT STD_LOGIC;
        compressdStream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        compressdStream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_s_dict_RAM_T2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (431 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (431 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (431 downto 0) );
    end component;



begin
    dict_U : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_s_dict_RAM_T2P_BRAM_1R1W
    generic map (
        DataWidth => 432,
        AddressRange => 2048,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dict_address0,
        ce0 => dict_ce0,
        we0 => dict_we0,
        d0 => dict_d0,
        address1 => dict_address1,
        ce1 => dict_ce1,
        we1 => dict_we1,
        d1 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d1,
        q1 => dict_q1);

    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138 : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start,
        ap_done => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_done,
        ap_idle => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_idle,
        ap_ready => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_ready,
        dict_address0 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address0,
        dict_ce0 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce0,
        dict_we0 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we0,
        dict_d0 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d0,
        dict_address1 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address1,
        dict_ce1 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce1,
        dict_we1 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we1,
        dict_d1 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d1);

    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143 : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start,
        ap_done => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_done,
        ap_idle => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_idle,
        ap_ready => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_ready,
        inStream_dout => inStream_dout,
        inStream_empty_n => inStream_empty_n,
        inStream_read => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_inStream_read,
        present_window_4_out => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_4_out,
        present_window_4_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_4_out_ap_vld,
        present_window_3_out => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_3_out,
        present_window_3_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_3_out_ap_vld,
        present_window_2_out => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_2_out,
        present_window_2_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_2_out_ap_vld,
        present_window_1_out => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_1_out,
        present_window_1_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_1_out_ap_vld,
        present_window_out => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_out,
        present_window_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_out_ap_vld,
        arrayidx55_promoted157_out => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx55_promoted157_out,
        arrayidx55_promoted157_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx55_promoted157_out_ap_vld,
        arrayidx46_3_promoted155_out => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx46_3_promoted155_out,
        arrayidx46_3_promoted155_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx46_3_promoted155_out_ap_vld,
        arrayidx65_promoted153_out => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx65_promoted153_out,
        arrayidx65_promoted153_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx65_promoted153_out_ap_vld,
        arrayidx61_promoted151_out => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx61_promoted151_out,
        arrayidx61_promoted151_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx61_promoted151_out_ap_vld,
        arrayidx58_promoted149_out => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx58_promoted149_out,
        arrayidx58_promoted149_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx58_promoted149_out_ap_vld);

    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159 : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start,
        ap_done => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_done,
        ap_idle => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_idle,
        ap_ready => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_ready,
        inStream_dout => inStream_dout,
        inStream_empty_n => inStream_empty_n,
        inStream_read => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_inStream_read,
        compressdStream_din => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_din,
        compressdStream_full_n => compressdStream_full_n,
        compressdStream_write => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_write,
        compressdStream_num_data_valid => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid,
        compressdStream_fifo_cap => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap,
        arrayidx55_promoted157_reload => arrayidx55_promoted157_loc_fu_96,
        arrayidx46_3_promoted155_reload => arrayidx46_3_promoted155_loc_fu_92,
        arrayidx65_promoted153_reload => arrayidx65_promoted153_loc_fu_88,
        arrayidx61_promoted151_reload => arrayidx61_promoted151_loc_fu_84,
        arrayidx58_promoted149_reload => arrayidx58_promoted149_loc_fu_80,
        sub34 => sub34_reg_510,
        dict_address0 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address0,
        dict_ce0 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce0,
        dict_we0 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_we0,
        dict_d0 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_d0,
        dict_address1 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address1,
        dict_ce1 => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce1,
        dict_q1 => dict_q1,
        present_window_15_out => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_15_out,
        present_window_15_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_15_out_ap_vld,
        present_window_14_out => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_14_out,
        present_window_14_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_14_out_ap_vld,
        present_window_13_out => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_13_out,
        present_window_13_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_13_out_ap_vld,
        present_window_12_out => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_12_out,
        present_window_12_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_12_out_ap_vld,
        present_window_11_out => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_11_out,
        present_window_11_out_ap_vld => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_11_out_ap_vld);

    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179 : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start,
        ap_done => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_done,
        ap_idle => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_idle,
        ap_ready => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_ready,
        compressdStream_din => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_din,
        compressdStream_full_n => compressdStream_full_n,
        compressdStream_write => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_write,
        compressdStream_num_data_valid => compressdStream_num_data_valid,
        compressdStream_fifo_cap => compressdStream_fifo_cap,
        select_ln80_4 => select_ln80_4_reg_544,
        select_ln80_3 => select_ln80_3_reg_539,
        select_ln80_2 => select_ln80_2_reg_534,
        select_ln80_1 => select_ln80_1_reg_529,
        select_ln80 => select_ln80_reg_524);

    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190 : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start,
        ap_done => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_done,
        ap_idle => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_idle,
        ap_ready => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_ready,
        inStream_dout => inStream_dout,
        inStream_empty_n => inStream_empty_n,
        inStream_read => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_inStream_read,
        compressdStream_din => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_din,
        compressdStream_full_n => compressdStream_full_n,
        compressdStream_write => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_write,
        compressdStream_num_data_valid => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid,
        compressdStream_fifo_cap => grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_ready = ap_const_logic_1)) then 
                    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_ready = ap_const_logic_1)) then 
                    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_ready = ap_const_logic_1)) then 
                    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_ready = ap_const_logic_1)) then 
                    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_ready = ap_const_logic_1)) then 
                    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx46_3_promoted155_out_ap_vld = ap_const_logic_1))) then
                arrayidx46_3_promoted155_loc_fu_92 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx46_3_promoted155_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx55_promoted157_out_ap_vld = ap_const_logic_1))) then
                arrayidx55_promoted157_loc_fu_96 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx55_promoted157_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx58_promoted149_out_ap_vld = ap_const_logic_1))) then
                arrayidx58_promoted149_loc_fu_80 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx58_promoted149_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx61_promoted151_out_ap_vld = ap_const_logic_1))) then
                arrayidx61_promoted151_loc_fu_84 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx61_promoted151_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx65_promoted153_out_ap_vld = ap_const_logic_1))) then
                arrayidx65_promoted153_loc_fu_88 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_arrayidx65_promoted153_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                icmp_ln63_reg_491 <= icmp_ln63_fu_198_p2;
                input_size_read_reg_396 <= input_size;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln87_reg_515 <= icmp_ln87_fu_264_p2;
                sub34_reg_510 <= sub34_fu_258_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_1_out_ap_vld = ap_const_logic_1))) then
                present_window_1_loc_fu_104 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_2_out_ap_vld = ap_const_logic_1))) then
                present_window_2_loc_fu_108 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_2_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_3_out_ap_vld = ap_const_logic_1))) then
                present_window_3_loc_fu_112 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_3_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_4_out_ap_vld = ap_const_logic_1))) then
                present_window_4_loc_fu_116 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_4_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_out_ap_vld = ap_const_logic_1))) then
                present_window_loc_fu_100 <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_present_window_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                select_ln80_1_reg_529 <= select_ln80_1_fu_322_p3;
                select_ln80_2_reg_534 <= select_ln80_2_fu_330_p3;
                select_ln80_3_reg_539 <= select_ln80_3_fu_338_p3;
                select_ln80_4_reg_544 <= select_ln80_4_fu_346_p3;
                select_ln80_reg_524 <= select_ln80_fu_314_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, icmp_ln63_fu_198_p2, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_done, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_block_state9_on_subcall_done, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln63_fu_198_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif (((icmp_ln63_fu_198_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_on_subcall_done)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_done)
    begin
        if ((grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_done)
    begin
        if ((grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(ap_block_state9_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state9_on_subcall_done)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, input_size_c2_full_n)
    begin
                ap_block_state1 <= ((input_size_c2_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_done, grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_done)
    begin
                ap_block_state3_on_subcall_done <= ((grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_done = ap_const_logic_0) or (grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_done = ap_const_logic_0));
    end process;


    ap_block_state9_on_subcall_done_assign_proc : process(icmp_ln63_reg_491, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_done)
    begin
                ap_block_state9_on_subcall_done <= ((icmp_ln63_reg_491 = ap_const_lv1_0) and (grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state9, ap_block_state9_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    compressdStream_din_assign_proc : process(icmp_ln63_reg_491, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_din, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_din, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_din, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if (((icmp_ln63_reg_491 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            compressdStream_din <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            compressdStream_din <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            compressdStream_din <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_din;
        else 
            compressdStream_din <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_din;
        end if; 
    end process;


    compressdStream_write_assign_proc : process(icmp_ln63_reg_491, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_write, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_write, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_write, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if (((icmp_ln63_reg_491 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            compressdStream_write <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            compressdStream_write <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_compressdStream_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            compressdStream_write <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_write;
        else 
            compressdStream_write <= ap_const_logic_0;
        end if; 
    end process;


    dict_address0_assign_proc : process(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address0, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_address0 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_address0 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address0;
        else 
            dict_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    dict_address1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address1, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_address1 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_address1 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_address1;
        else 
            dict_address1 <= "XXXXXXXXXXX";
        end if; 
    end process;


    dict_ce0_assign_proc : process(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce0, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_ce0 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_ce0 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce0;
        else 
            dict_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dict_ce1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce1, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_ce1 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_ce1 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_ce1;
        else 
            dict_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    dict_d0_assign_proc : process(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d0, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_d0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_d0 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_d0 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_d0;
        else 
            dict_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dict_we0_assign_proc : process(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we0, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_we0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_we0 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_dict_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_we0 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we0;
        else 
            dict_we0 <= ap_const_logic_0;
        end if; 
    end process;


    dict_we1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we1, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_we1 <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_dict_we1;
        else 
            dict_we1 <= ap_const_logic_0;
        end if; 
    end process;

    grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_ap_start_reg;
    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_dict_flush_fu_138_ap_start_reg;
    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_ap_start_reg;
    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap0(4 - 1 downto 0);
    
    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap0_proc : process(compressdStream_fifo_cap)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap0_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_3(5 - 1 downto 0);
        v0_cpy := compressdStream_fifo_cap;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_3(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap0_i in 0 to 32-1 loop
                v0_cpy(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap0_i) := compressdStream_fifo_cap(32-1-grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap0_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_fifo_cap0 <= resvalue(32-1 downto 0);
    end process;

    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid0(4 - 1 downto 0);
    
    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid0_proc : process(compressdStream_num_data_valid)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid0_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_3(5 - 1 downto 0);
        v0_cpy := compressdStream_num_data_valid;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_3(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid0_i in 0 to 32-1 loop
                v0_cpy(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid0_i) := compressdStream_num_data_valid(32-1-grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid0_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_compressdStream_num_data_valid0 <= resvalue(32-1 downto 0);
    end process;

    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_leftover_fu_179_ap_start_reg;
    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_ap_start_reg;
    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap0(4 - 1 downto 0);
    
    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap0_proc : process(compressdStream_fifo_cap)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap0_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_3(5 - 1 downto 0);
        v0_cpy := compressdStream_fifo_cap;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_3(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap0_i in 0 to 32-1 loop
                v0_cpy(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap0_i) := compressdStream_fifo_cap(32-1-grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap0_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_fifo_cap0 <= resvalue(32-1 downto 0);
    end process;

    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid0(4 - 1 downto 0);
    
    grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid0_proc : process(compressdStream_num_data_valid)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid0_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_3(5 - 1 downto 0);
        v0_cpy := compressdStream_num_data_valid;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_3(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid0_i in 0 to 32-1 loop
                v0_cpy(grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid0_i) := compressdStream_num_data_valid(32-1-grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid0_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_compressdStream_num_data_valid0 <= resvalue(32-1 downto 0);
    end process;

    icmp_ln63_fu_198_p2 <= "1" when (input_size = ap_const_lv32_0) else "0";
    icmp_ln87_fu_264_p2 <= "1" when (unsigned(sub34_fu_258_p2) > unsigned(ap_const_lv32_5)) else "0";

    inStream_read_assign_proc : process(icmp_ln63_reg_491, grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_inStream_read, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_inStream_read, grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_inStream_read, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state9)
    begin
        if (((icmp_ln63_reg_491 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            inStream_read <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_left_bytes_fu_190_inStream_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            inStream_read <= grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_inStream_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            inStream_read <= grp_lzCompress_6_4_65536_6_1_2048_64_Outline_VITIS_LOOP_82_2_fu_143_inStream_read;
        else 
            inStream_read <= ap_const_logic_0;
        end if; 
    end process;


    input_size_c2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, input_size_c2_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_size_c2_blk_n <= input_size_c2_full_n;
        else 
            input_size_c2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_size_c2_din <= input_size;

    input_size_c2_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_size_c2_write <= ap_const_logic_1;
        else 
            input_size_c2_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state9, ap_block_state9_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln80_1_fu_322_p3 <= 
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_14_out when (icmp_ln87_reg_515(0) = '1') else 
        present_window_3_loc_fu_112;
    select_ln80_2_fu_330_p3 <= 
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_13_out when (icmp_ln87_reg_515(0) = '1') else 
        present_window_2_loc_fu_108;
    select_ln80_3_fu_338_p3 <= 
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_12_out when (icmp_ln87_reg_515(0) = '1') else 
        present_window_1_loc_fu_104;
    select_ln80_4_fu_346_p3 <= 
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_11_out when (icmp_ln87_reg_515(0) = '1') else 
        present_window_loc_fu_100;
    select_ln80_fu_314_p3 <= 
        grp_lzCompress_6_4_65536_6_1_2048_64_Pipeline_lz_compress_fu_159_present_window_15_out when (icmp_ln87_reg_515(0) = '1') else 
        present_window_4_loc_fu_116;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub34_fu_258_p2 <= std_logic_vector(unsigned(input_size_read_reg_396) + unsigned(ap_const_lv32_FFFFFFC0));
end behav;
