-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lz4CompressEngineRun_lzBooster_255_16384_64_Pipeline_lz_booster is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bestMatchStream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    bestMatchStream_empty_n : IN STD_LOGIC;
    bestMatchStream_read : OUT STD_LOGIC;
    bestMatchStream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    bestMatchStream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    boosterStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    boosterStream_full_n : IN STD_LOGIC;
    boosterStream_write : OUT STD_LOGIC;
    boosterStream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    boosterStream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    sub : IN STD_LOGIC_VECTOR (31 downto 0);
    outValue_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    outValue_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of lz4CompressEngineRun_lzBooster_255_16384_64_Pipeline_lz_booster is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln573_reg_629 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal icmp_ln573_reg_629_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln589_reg_663 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln591_1_reg_672 : STD_LOGIC_VECTOR (0 downto 0);
    signal outFlag_reg_676 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op112_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln573_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal bestMatchStream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal boosterStream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal i_4_reg_622 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_4_reg_622_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln573_reg_629_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal outValue_2_reg_633 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal tCh_fu_264_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tCh_reg_640 : STD_LOGIC_VECTOR (7 downto 0);
    signal tLen_reg_645 : STD_LOGIC_VECTOR (7 downto 0);
    signal tOffset_reg_651 : STD_LOGIC_VECTOR (15 downto 0);
    signal boostFlag_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boostFlag_reg_656 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln589_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln591_1_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal outFlag_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln601_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln601_reg_680 : STD_LOGIC_VECTOR (0 downto 0);
    signal outValue_load_reg_689 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal local_mem_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal local_mem_address1 : STD_LOGIC_VECTOR (13 downto 0);
    signal local_mem_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_matchFlag_426_phi_fu_176_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter2_matchFlag_426_reg_173 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_skip_len_424_phi_fu_186_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal skip_len_7_fu_402_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_skip_len_424_reg_183 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_phi_fu_196_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_empty_reg_193 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln586_fu_301_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln613_fu_331_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln613_2_fu_392_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln613_1_fu_519_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal skip_len_fu_78 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal skip_len_5_fu_325_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln566_fu_410_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln614_fu_461_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal match_ch_fu_82 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_sig_allocacmp_match_ch_load : STD_LOGIC_VECTOR (7 downto 0);
    signal i_fu_86 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal i_5_fu_250_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_i_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal outValue_fu_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal outValue_1_fu_509_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal matchFlag_fu_94 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal match_len_fu_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal match_len_3_fu_489_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal match_loc_fu_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal match_loc_5_fu_373_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal match_loc_4_fu_495_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal local_mem_we0_local : STD_LOGIC;
    signal local_mem_ce0_local : STD_LOGIC;
    signal local_mem_ce1_local : STD_LOGIC;
    signal local_mem_address1_local : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_285_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln573_1_fu_261_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln573_fu_315_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln591_1_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln591_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln591_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln597_fu_370_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln562_1_fu_378_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal skip_len_6_fu_397_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln594_fu_505_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln562_fu_501_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_enable_operation_39 : BOOLEAN;
    signal ap_enable_state2_pp0_iter1_stage0 : BOOLEAN;
    signal ap_predicate_op51_load_state3 : BOOLEAN;
    signal ap_enable_operation_51 : BOOLEAN;
    signal ap_enable_state3_pp0_iter2_stage0 : BOOLEAN;
    signal ap_predicate_op107_load_state4 : BOOLEAN;
    signal ap_enable_operation_107 : BOOLEAN;
    signal ap_enable_state4_pp0_iter3_stage0 : BOOLEAN;
    signal ap_predicate_op67_load_state3 : BOOLEAN;
    signal ap_enable_operation_67 : BOOLEAN;
    signal ap_predicate_op109_load_state4 : BOOLEAN;
    signal ap_enable_operation_109 : BOOLEAN;
    signal ap_predicate_op101_load_state3 : BOOLEAN;
    signal ap_enable_operation_101 : BOOLEAN;
    signal ap_predicate_op114_load_state4 : BOOLEAN;
    signal ap_enable_operation_114 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_274 : BOOLEAN;
    signal ap_condition_543 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component lz4CompressEngineRun_lzBooster_255_16384_64_Pipeline_lz_booster_local_mem_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component lz4CompressEngineRun_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    local_mem_U : component lz4CompressEngineRun_lzBooster_255_16384_64_Pipeline_lz_booster_local_mem_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 16384,
        AddressWidth => 14)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => local_mem_address0,
        ce0 => local_mem_ce0_local,
        we0 => local_mem_we0_local,
        d0 => tCh_fu_264_p1,
        address1 => local_mem_address1,
        ce1 => local_mem_ce1_local,
        q1 => local_mem_q1);

    flow_control_loop_pipe_sequential_init_U : component lz4CompressEngineRun_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln573_fu_244_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_86 <= i_5_fu_250_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_86 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    matchFlag_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_1 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0))) then 
                matchFlag_fu_94 <= ap_const_lv1_1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (outFlag_fu_382_p2 = ap_const_lv1_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0))) then 
                matchFlag_fu_94 <= ap_phi_mux_matchFlag_426_phi_fu_176_p4;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln601_fu_387_p2 = ap_const_lv1_1) and (outFlag_fu_382_p2 = ap_const_lv1_0) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)))) then 
                matchFlag_fu_94 <= ap_const_lv1_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln601_fu_387_p2 = ap_const_lv1_0) and (outFlag_fu_382_p2 = ap_const_lv1_0) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0))) then 
                matchFlag_fu_94 <= boostFlag_reg_656;
            end if; 
        end if;
    end process;

    match_len_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                match_len_fu_98 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_1 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0))) then 
                match_len_fu_98 <= match_len_3_fu_489_p2;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln601_fu_387_p2 = ap_const_lv1_1) and (outFlag_fu_382_p2 = ap_const_lv1_0) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (outFlag_fu_382_p2 = ap_const_lv1_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln601_fu_387_p2 = ap_const_lv1_0) and (outFlag_fu_382_p2 = ap_const_lv1_0) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)))) then 
                match_len_fu_98 <= ap_const_lv32_1;
            end if; 
        end if;
    end process;

    match_loc_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                match_loc_fu_102 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_1 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0))) then 
                match_loc_fu_102 <= match_loc_4_fu_495_p2;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln601_fu_387_p2 = ap_const_lv1_1) and (outFlag_fu_382_p2 = ap_const_lv1_0) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (outFlag_fu_382_p2 = ap_const_lv1_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln601_fu_387_p2 = ap_const_lv1_0) and (outFlag_fu_382_p2 = ap_const_lv1_0) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)))) then 
                match_loc_fu_102 <= match_loc_5_fu_373_p2;
            end if; 
        end if;
    end process;

    outValue_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_1 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0))) then 
                outValue_fu_90 <= outValue_1_fu_509_p4;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln601_fu_387_p2 = ap_const_lv1_1) and (outFlag_fu_382_p2 = ap_const_lv1_0) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (outFlag_fu_382_p2 = ap_const_lv1_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln601_fu_387_p2 = ap_const_lv1_0) and (outFlag_fu_382_p2 = ap_const_lv1_0) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)))) then 
                outValue_fu_90 <= outValue_2_reg_633;
            end if; 
        end if;
    end process;

    skip_len_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (outFlag_fu_382_p2 = ap_const_lv1_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0))) then 
                skip_len_fu_78 <= zext_ln614_fu_461_p1;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_1 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln601_fu_387_p2 = ap_const_lv1_1) and (outFlag_fu_382_p2 = ap_const_lv1_0) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)))) then 
                skip_len_fu_78 <= ap_const_lv16_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln601_fu_387_p2 = ap_const_lv1_0) and (outFlag_fu_382_p2 = ap_const_lv1_0) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0))) then 
                skip_len_fu_78 <= zext_ln566_fu_410_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_0) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0))) then 
                skip_len_fu_78 <= skip_len_5_fu_325_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                and_ln591_1_reg_672 <= and_ln591_1_fu_364_p2;
                icmp_ln589_reg_663 <= icmp_ln589_fu_319_p2;
                icmp_ln601_reg_680 <= icmp_ln601_fu_387_p2;
                outFlag_reg_676 <= outFlag_fu_382_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_4_reg_622 <= ap_sig_allocacmp_i_4;
                i_4_reg_622_pp0_iter1_reg <= i_4_reg_622;
                icmp_ln573_reg_629 <= icmp_ln573_fu_244_p2;
                icmp_ln573_reg_629_pp0_iter1_reg <= icmp_ln573_reg_629;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                boostFlag_reg_656 <= boostFlag_fu_295_p2;
                outValue_2_reg_633 <= bestMatchStream_dout;
                tCh_reg_640 <= tCh_fu_264_p1;
                tLen_reg_645 <= bestMatchStream_dout(15 downto 8);
                tOffset_reg_651 <= bestMatchStream_dout(31 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln573_reg_629_pp0_iter2_reg <= icmp_ln573_reg_629_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                match_ch_fu_82 <= ap_phi_mux_empty_phi_fu_196_p10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                outValue_load_reg_689 <= outValue_fu_90;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    and_ln591_1_fu_364_p2 <= (matchFlag_fu_94 and and_ln591_fu_358_p2);
    and_ln591_fu_358_p2 <= (icmp_ln591_fu_347_p2 and icmp_ln591_1_fu_353_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_state4_pp0_stage0_iter3_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_state4_pp0_stage0_iter3_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_state4_pp0_stage0_iter3_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_state4_pp0_stage0_iter3_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_grp1_assign_proc : process(bestMatchStream_empty_n, icmp_ln573_reg_629)
    begin
                ap_block_state2_pp0_stage0_iter1_grp1 <= ((icmp_ln573_reg_629 = ap_const_lv1_0) and (bestMatchStream_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter3_grp1_assign_proc : process(boosterStream_full_n, ap_predicate_op112_write_state4)
    begin
                ap_block_state4_pp0_stage0_iter3_grp1 <= ((ap_predicate_op112_write_state4 = ap_const_boolean_1) and (boosterStream_full_n = ap_const_logic_0));
    end process;


    ap_condition_274_assign_proc : process(icmp_ln573_reg_629_pp0_iter1_reg, icmp_ln589_fu_319_p2, and_ln591_1_fu_364_p2, outFlag_fu_382_p2)
    begin
                ap_condition_274 <= ((ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (outFlag_fu_382_p2 = ap_const_lv1_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_condition_543_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_grp1, icmp_ln573_reg_629_pp0_iter1_reg)
    begin
                ap_condition_543 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln573_fu_244_p2)
    begin
        if (((icmp_ln573_fu_244_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, icmp_ln573_reg_629_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_101_assign_proc : process(ap_predicate_op101_load_state3)
    begin
                ap_enable_operation_101 <= (ap_predicate_op101_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_107_assign_proc : process(ap_predicate_op107_load_state4)
    begin
                ap_enable_operation_107 <= (ap_predicate_op107_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_109_assign_proc : process(ap_predicate_op109_load_state4)
    begin
                ap_enable_operation_109 <= (ap_predicate_op109_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_114_assign_proc : process(ap_predicate_op114_load_state4)
    begin
                ap_enable_operation_114 <= (ap_predicate_op114_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_39_assign_proc : process(icmp_ln573_reg_629)
    begin
                ap_enable_operation_39 <= (icmp_ln573_reg_629 = ap_const_lv1_0);
    end process;


    ap_enable_operation_51_assign_proc : process(ap_predicate_op51_load_state3)
    begin
                ap_enable_operation_51 <= (ap_predicate_op51_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_67_assign_proc : process(ap_predicate_op67_load_state3)
    begin
                ap_enable_operation_67 <= (ap_predicate_op67_load_state3 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_enable_state2_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state2_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state3_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
                ap_enable_state3_pp0_iter2_stage0 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state4_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3)
    begin
                ap_enable_state4_pp0_iter3_stage0 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_empty_phi_fu_196_p10_assign_proc : process(icmp_ln573_reg_629_pp0_iter2_reg, icmp_ln589_reg_663, and_ln591_1_reg_672, outFlag_reg_676, icmp_ln601_reg_680, local_mem_q1, ap_phi_reg_pp0_iter3_empty_reg_193)
    begin
        if ((((outFlag_reg_676 = ap_const_lv1_1) and (icmp_ln589_reg_663 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln591_1_reg_672)) or ((icmp_ln589_reg_663 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln591_1_reg_672)) or ((outFlag_reg_676 = ap_const_lv1_0) and (icmp_ln589_reg_663 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln591_1_reg_672) and (icmp_ln601_reg_680 = ap_const_lv1_1)) or ((outFlag_reg_676 = ap_const_lv1_0) and (icmp_ln589_reg_663 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln591_1_reg_672) and (icmp_ln601_reg_680 = ap_const_lv1_0)) or ((icmp_ln589_reg_663 = ap_const_lv1_0) and (icmp_ln573_reg_629_pp0_iter2_reg = ap_const_lv1_0)))) then 
            ap_phi_mux_empty_phi_fu_196_p10 <= local_mem_q1;
        else 
            ap_phi_mux_empty_phi_fu_196_p10 <= ap_phi_reg_pp0_iter3_empty_reg_193;
        end if; 
    end process;


    ap_phi_mux_matchFlag_426_phi_fu_176_p4_assign_proc : process(boostFlag_reg_656, icmp_ln601_fu_387_p2, ap_phi_reg_pp0_iter2_matchFlag_426_reg_173, ap_condition_274)
    begin
        if ((ap_const_boolean_1 = ap_condition_274)) then
            if ((icmp_ln601_fu_387_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_matchFlag_426_phi_fu_176_p4 <= ap_const_lv1_0;
            elsif ((icmp_ln601_fu_387_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_matchFlag_426_phi_fu_176_p4 <= boostFlag_reg_656;
            else 
                ap_phi_mux_matchFlag_426_phi_fu_176_p4 <= ap_phi_reg_pp0_iter2_matchFlag_426_reg_173;
            end if;
        else 
            ap_phi_mux_matchFlag_426_phi_fu_176_p4 <= ap_phi_reg_pp0_iter2_matchFlag_426_reg_173;
        end if; 
    end process;


    ap_phi_mux_skip_len_424_phi_fu_186_p4_assign_proc : process(icmp_ln601_fu_387_p2, skip_len_7_fu_402_p3, ap_phi_reg_pp0_iter2_skip_len_424_reg_183, ap_condition_274)
    begin
        if ((ap_const_boolean_1 = ap_condition_274)) then
            if ((icmp_ln601_fu_387_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_skip_len_424_phi_fu_186_p4 <= ap_const_lv8_0;
            elsif ((icmp_ln601_fu_387_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_skip_len_424_phi_fu_186_p4 <= skip_len_7_fu_402_p3;
            else 
                ap_phi_mux_skip_len_424_phi_fu_186_p4 <= ap_phi_reg_pp0_iter2_skip_len_424_reg_183;
            end if;
        else 
            ap_phi_mux_skip_len_424_phi_fu_186_p4 <= ap_phi_reg_pp0_iter2_skip_len_424_reg_183;
        end if; 
    end process;

    ap_phi_reg_pp0_iter2_matchFlag_426_reg_173 <= "X";
    ap_phi_reg_pp0_iter2_skip_len_424_reg_183 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter3_empty_reg_193 <= "XXXXXXXX";

    ap_predicate_op101_load_state3_assign_proc : process(icmp_ln573_reg_629_pp0_iter1_reg, icmp_ln589_fu_319_p2, and_ln591_1_fu_364_p2)
    begin
                ap_predicate_op101_load_state3 <= ((ap_const_lv1_1 = and_ln591_1_fu_364_p2) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op107_load_state4_assign_proc : process(icmp_ln573_reg_629_pp0_iter2_reg, icmp_ln589_reg_663)
    begin
                ap_predicate_op107_load_state4 <= ((icmp_ln589_reg_663 = ap_const_lv1_0) and (icmp_ln573_reg_629_pp0_iter2_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op109_load_state4_assign_proc : process(icmp_ln573_reg_629_pp0_iter2_reg, icmp_ln589_reg_663, and_ln591_1_reg_672)
    begin
                ap_predicate_op109_load_state4 <= ((icmp_ln589_reg_663 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln591_1_reg_672));
    end process;


    ap_predicate_op112_write_state4_assign_proc : process(icmp_ln573_reg_629_pp0_iter2_reg, icmp_ln589_reg_663, and_ln591_1_reg_672, outFlag_reg_676)
    begin
                ap_predicate_op112_write_state4 <= ((outFlag_reg_676 = ap_const_lv1_1) and (icmp_ln589_reg_663 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln591_1_reg_672));
    end process;


    ap_predicate_op114_load_state4_assign_proc : process(icmp_ln573_reg_629_pp0_iter2_reg, icmp_ln589_reg_663, and_ln591_1_reg_672)
    begin
                ap_predicate_op114_load_state4 <= ((icmp_ln589_reg_663 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln591_1_reg_672));
    end process;


    ap_predicate_op51_load_state3_assign_proc : process(icmp_ln573_reg_629_pp0_iter1_reg, icmp_ln589_fu_319_p2)
    begin
                ap_predicate_op51_load_state3 <= ((icmp_ln589_fu_319_p2 = ap_const_lv1_0) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op67_load_state3_assign_proc : process(icmp_ln573_reg_629_pp0_iter1_reg, icmp_ln589_fu_319_p2, and_ln591_1_fu_364_p2)
    begin
                ap_predicate_op67_load_state3 <= ((ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, i_fu_86, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_4 <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_i_4 <= i_fu_86;
        end if; 
    end process;


    ap_sig_allocacmp_match_ch_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_grp1, ap_phi_mux_empty_phi_fu_196_p10, match_ch_fu_82)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_match_ch_load <= ap_phi_mux_empty_phi_fu_196_p10;
        else 
            ap_sig_allocacmp_match_ch_load <= match_ch_fu_82;
        end if; 
    end process;


    bestMatchStream_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, bestMatchStream_empty_n, icmp_ln573_reg_629, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln573_reg_629 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bestMatchStream_blk_n <= bestMatchStream_empty_n;
        else 
            bestMatchStream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bestMatchStream_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln573_reg_629, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln573_reg_629 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bestMatchStream_read <= ap_const_logic_1;
        else 
            bestMatchStream_read <= ap_const_logic_0;
        end if; 
    end process;

    boostFlag_fu_295_p2 <= "1" when (tmp_fu_285_p4 = ap_const_lv2_0) else "0";

    boosterStream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, boosterStream_full_n, ap_predicate_op112_write_state4, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_predicate_op112_write_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            boosterStream_blk_n <= boosterStream_full_n;
        else 
            boosterStream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    boosterStream_din <= outValue_load_reg_689;

    boosterStream_write_assign_proc : process(ap_enable_reg_pp0_iter3, ap_predicate_op112_write_state4, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_predicate_op112_write_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            boosterStream_write <= ap_const_logic_1;
        else 
            boosterStream_write <= ap_const_logic_0;
        end if; 
    end process;

    i_5_fu_250_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_4) + unsigned(ap_const_lv32_1));
    icmp_ln573_fu_244_p2 <= "1" when (ap_sig_allocacmp_i_4 = sub) else "0";
    icmp_ln589_fu_319_p2 <= "1" when (skip_len_fu_78 = ap_const_lv16_0) else "0";
    icmp_ln591_1_fu_353_p2 <= "1" when (tCh_reg_640 = ap_sig_allocacmp_match_ch_load) else "0";
    icmp_ln591_fu_347_p2 <= "1" when (unsigned(match_len_fu_98) < unsigned(ap_const_lv32_FF)) else "0";
    icmp_ln601_fu_387_p2 <= "1" when (tLen_reg_645 = ap_const_lv8_0) else "0";
    local_mem_address0 <= zext_ln586_fu_301_p1(14 - 1 downto 0);
    local_mem_address1 <= local_mem_address1_local;

    local_mem_address1_local_assign_proc : process(icmp_ln589_fu_319_p2, and_ln591_1_fu_364_p2, zext_ln613_fu_331_p1, zext_ln613_2_fu_392_p1, zext_ln613_1_fu_519_p1, ap_condition_543)
    begin
        if ((ap_const_boolean_1 = ap_condition_543)) then
            if (((ap_const_lv1_1 = and_ln591_1_fu_364_p2) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1))) then 
                local_mem_address1_local <= zext_ln613_1_fu_519_p1(14 - 1 downto 0);
            elsif (((ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1))) then 
                local_mem_address1_local <= zext_ln613_2_fu_392_p1(14 - 1 downto 0);
            elsif ((icmp_ln589_fu_319_p2 = ap_const_lv1_0)) then 
                local_mem_address1_local <= zext_ln613_fu_331_p1(14 - 1 downto 0);
            else 
                local_mem_address1_local <= "XXXXXXXXXXXXXX";
            end if;
        else 
            local_mem_address1_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    local_mem_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_mem_ce0_local <= ap_const_logic_1;
        else 
            local_mem_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    local_mem_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln573_reg_629_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp1, icmp_ln589_fu_319_p2, and_ln591_1_fu_364_p2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_1 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_0 = and_ln591_1_fu_364_p2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln589_fu_319_p2 = ap_const_lv1_0) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_0)))) then 
            local_mem_ce1_local <= ap_const_logic_1;
        else 
            local_mem_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    local_mem_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln573_reg_629, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln573_reg_629 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_mem_we0_local <= ap_const_logic_1;
        else 
            local_mem_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    match_len_3_fu_489_p2 <= std_logic_vector(unsigned(match_len_fu_98) + unsigned(ap_const_lv32_1));
    match_loc_4_fu_495_p2 <= std_logic_vector(unsigned(match_loc_fu_102) + unsigned(ap_const_lv32_1));
    match_loc_5_fu_373_p2 <= std_logic_vector(unsigned(i_4_reg_622_pp0_iter1_reg) - unsigned(zext_ln597_fu_370_p1));
    outFlag_fu_382_p2 <= "0" when (i_4_reg_622_pp0_iter1_reg = ap_const_lv32_0) else "1";
    outValue_1_fu_509_p4 <= (outValue_fu_90(31 downto 16) & trunc_ln594_fu_505_p1 & outValue_fu_90(7 downto 0));
    outValue_out <= outValue_fu_90;

    outValue_out_ap_vld_assign_proc : process(icmp_ln573_reg_629_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp1, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln573_reg_629_pp0_iter1_reg = ap_const_lv1_1))) then 
            outValue_out_ap_vld <= ap_const_logic_1;
        else 
            outValue_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    skip_len_5_fu_325_p2 <= std_logic_vector(unsigned(skip_len_fu_78) + unsigned(ap_const_lv16_FFFF));
    skip_len_6_fu_397_p2 <= std_logic_vector(unsigned(tLen_reg_645) + unsigned(ap_const_lv8_FF));
    skip_len_7_fu_402_p3 <= 
        ap_const_lv8_0 when (boostFlag_reg_656(0) = '1') else 
        skip_len_6_fu_397_p2;
    tCh_fu_264_p1 <= bestMatchStream_dout(8 - 1 downto 0);
    tmp_fu_285_p4 <= bestMatchStream_dout(31 downto 30);
    trunc_ln562_1_fu_378_p1 <= match_loc_5_fu_373_p2(14 - 1 downto 0);
    trunc_ln562_fu_501_p1 <= match_loc_4_fu_495_p2(14 - 1 downto 0);
    trunc_ln573_1_fu_261_p1 <= i_4_reg_622(14 - 1 downto 0);
    trunc_ln573_fu_315_p1 <= match_loc_fu_102(14 - 1 downto 0);
    trunc_ln594_fu_505_p1 <= match_len_3_fu_489_p2(8 - 1 downto 0);
    zext_ln566_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(skip_len_7_fu_402_p3),16));
    zext_ln586_fu_301_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln573_1_fu_261_p1),64));
    zext_ln597_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tOffset_reg_651),32));
    zext_ln613_1_fu_519_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln562_fu_501_p1),64));
    zext_ln613_2_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln562_1_fu_378_p1),64));
    zext_ln613_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln573_fu_315_p1),64));
    zext_ln614_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_skip_len_424_phi_fu_186_p4),16));
end behav;
