-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lz4CompressEngineRun_lz4CompressPart1_4096_1_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    boosterStream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    boosterStream_empty_n : IN STD_LOGIC;
    boosterStream_read : OUT STD_LOGIC;
    boosterStream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    boosterStream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    lit_outStream_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    lit_outStream_full_n : IN STD_LOGIC;
    lit_outStream_write : OUT STD_LOGIC;
    lit_outStream_num_data_valid : IN STD_LOGIC_VECTOR (12 downto 0);
    lit_outStream_fifo_cap : IN STD_LOGIC_VECTOR (12 downto 0);
    lenOffset_Stream_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    lenOffset_Stream_full_n : IN STD_LOGIC;
    lenOffset_Stream_write : OUT STD_LOGIC;
    lenOffset_Stream_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    lenOffset_Stream_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    input_size_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    input_size_empty_n : IN STD_LOGIC;
    input_size_read : OUT STD_LOGIC;
    input_size_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    input_size_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    max_lit_limit : OUT STD_LOGIC_VECTOR (31 downto 0);
    max_lit_limit_ap_vld : OUT STD_LOGIC;
    input_size_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    input_size_c_full_n : IN STD_LOGIC;
    input_size_c_write : OUT STD_LOGIC;
    input_size_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    input_size_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of lz4CompressEngineRun_lz4CompressPart1_4096_1_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001000000000000";
    constant ap_const_lv64_100003090309 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000100000000000000000011000010010000001100001001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal boosterStream_blk_n : STD_LOGIC;
    signal icmp_ln51_fu_153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lenOffset_Stream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln51_reg_232 : STD_LOGIC_VECTOR (0 downto 0);
    signal lit_count_loc_load_load_fu_197_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_size_blk_n : STD_LOGIC;
    signal input_size_c_blk_n : STD_LOGIC;
    signal input_size_4_reg_226 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal boosterStream_read_reg_236 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_fu_159_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_reg_241 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_start : STD_LOGIC;
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_done : STD_LOGIC;
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_idle : STD_LOGIC;
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_ready : STD_LOGIC;
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_boosterStream_read : STD_LOGIC;
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_outStream_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_outStream_write : STD_LOGIC;
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lenOffset_Stream_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lenOffset_Stream_write : STD_LOGIC;
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out_ap_vld : STD_LOGIC;
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_flag_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_flag_out_ap_vld : STD_LOGIC;
    signal tmpValue_fu_205_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_mux_tmpValue_1_phi_fu_109_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_predicate_op31_write_state4 : BOOLEAN;
    signal ap_block_state4 : BOOLEAN;
    signal ap_phi_mux_lit_count_flag_phi_fu_120_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_lit_count_flag_1_phi_fu_130_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal max_lit_limit_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component lz4CompressEngineRun_lz4CompressPart1_4096_1_Pipeline_lz4_divide IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        boosterStream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        boosterStream_empty_n : IN STD_LOGIC;
        boosterStream_read : OUT STD_LOGIC;
        boosterStream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        boosterStream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        lit_outStream_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        lit_outStream_full_n : IN STD_LOGIC;
        lit_outStream_write : OUT STD_LOGIC;
        lit_outStream_num_data_valid : IN STD_LOGIC_VECTOR (12 downto 0);
        lit_outStream_fifo_cap : IN STD_LOGIC_VECTOR (12 downto 0);
        lenOffset_Stream_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        lenOffset_Stream_full_n : IN STD_LOGIC;
        lenOffset_Stream_write : OUT STD_LOGIC;
        lenOffset_Stream_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
        lenOffset_Stream_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
        empty : IN STD_LOGIC_VECTOR (31 downto 0);
        input_size_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        sub : IN STD_LOGIC_VECTOR (31 downto 0);
        lit_count_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        lit_count_out_ap_vld : OUT STD_LOGIC;
        lit_count_flag_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        lit_count_flag_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138 : component lz4CompressEngineRun_lz4CompressPart1_4096_1_Pipeline_lz4_divide
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_start,
        ap_done => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_done,
        ap_idle => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_idle,
        ap_ready => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_ready,
        boosterStream_dout => boosterStream_dout,
        boosterStream_empty_n => boosterStream_empty_n,
        boosterStream_read => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_boosterStream_read,
        boosterStream_num_data_valid => ap_const_lv4_0,
        boosterStream_fifo_cap => ap_const_lv4_0,
        lit_outStream_din => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_outStream_din,
        lit_outStream_full_n => lit_outStream_full_n,
        lit_outStream_write => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_outStream_write,
        lit_outStream_num_data_valid => ap_const_lv13_0,
        lit_outStream_fifo_cap => ap_const_lv13_0,
        lenOffset_Stream_din => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lenOffset_Stream_din,
        lenOffset_Stream_full_n => lenOffset_Stream_full_n,
        lenOffset_Stream_write => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lenOffset_Stream_write,
        lenOffset_Stream_num_data_valid => ap_const_lv6_0,
        lenOffset_Stream_fifo_cap => ap_const_lv6_0,
        empty => boosterStream_read_reg_236,
        input_size_4 => input_size_4_reg_226,
        sub => sub_reg_241,
        lit_count_out => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out,
        lit_count_out_ap_vld => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out_ap_vld,
        lit_count_flag_out => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_flag_out,
        lit_count_flag_out_ap_vld => grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_flag_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_ready = ap_const_logic_1)) then 
                    grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    max_lit_limit_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                max_lit_limit_preg <= ap_const_lv32_0;
            else
                if (((icmp_ln51_reg_232 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then 
                    max_lit_limit_preg <= ap_phi_mux_lit_count_flag_1_phi_fu_130_p4;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                boosterStream_read_reg_236 <= boosterStream_dout;
                icmp_ln51_reg_232 <= icmp_ln51_fu_153_p2;
                input_size_4_reg_226 <= input_size_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                sub_reg_241 <= sub_fu_159_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, icmp_ln51_fu_153_p2, ap_CS_fsm_state4, ap_block_state1, grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_done, ap_block_state4, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln51_fu_153_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif (((icmp_ln51_fu_153_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_done)
    begin
        if ((grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4)
    begin
        if ((ap_const_boolean_1 = ap_block_state4)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, boosterStream_empty_n, input_size_empty_n, input_size_c_full_n, icmp_ln51_fu_153_p2)
    begin
                ap_block_state1 <= ((input_size_c_full_n = ap_const_logic_0) or (input_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((icmp_ln51_fu_153_p2 = ap_const_lv1_0) and (boosterStream_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state4_assign_proc : process(lenOffset_Stream_full_n, ap_predicate_op31_write_state4)
    begin
                ap_block_state4 <= ((lenOffset_Stream_full_n = ap_const_logic_0) and (ap_predicate_op31_write_state4 = ap_const_boolean_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4, ap_block_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_lit_count_flag_1_phi_fu_130_p4_assign_proc : process(ap_CS_fsm_state4, icmp_ln51_reg_232, grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out, grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_flag_out, ap_phi_mux_lit_count_flag_phi_fu_120_p4)
    begin
        if (((icmp_ln51_reg_232 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
            if (not((grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out = ap_const_lv32_0))) then 
                ap_phi_mux_lit_count_flag_1_phi_fu_130_p4 <= ap_phi_mux_lit_count_flag_phi_fu_120_p4;
            elsif ((grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out = ap_const_lv32_0)) then 
                ap_phi_mux_lit_count_flag_1_phi_fu_130_p4 <= grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_flag_out;
            else 
                ap_phi_mux_lit_count_flag_1_phi_fu_130_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_lit_count_flag_1_phi_fu_130_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_lit_count_flag_phi_fu_120_p4_assign_proc : process(ap_CS_fsm_state4, icmp_ln51_reg_232, lit_count_loc_load_load_fu_197_p1, grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out, grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_flag_out)
    begin
        if (((icmp_ln51_reg_232 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
            if ((lit_count_loc_load_load_fu_197_p1 = ap_const_lv32_1000)) then 
                ap_phi_mux_lit_count_flag_phi_fu_120_p4 <= ap_const_lv32_1;
            elsif ((not((grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out = ap_const_lv32_0)) and not((lit_count_loc_load_load_fu_197_p1 = ap_const_lv32_1000)))) then 
                ap_phi_mux_lit_count_flag_phi_fu_120_p4 <= grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_flag_out;
            else 
                ap_phi_mux_lit_count_flag_phi_fu_120_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_lit_count_flag_phi_fu_120_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_tmpValue_1_phi_fu_109_p4_assign_proc : process(ap_CS_fsm_state4, icmp_ln51_reg_232, lit_count_loc_load_load_fu_197_p1, grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out, tmpValue_fu_205_p3)
    begin
        if (((icmp_ln51_reg_232 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
            if ((lit_count_loc_load_load_fu_197_p1 = ap_const_lv32_1000)) then 
                ap_phi_mux_tmpValue_1_phi_fu_109_p4 <= ap_const_lv64_100003090309;
            elsif ((not((grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out = ap_const_lv32_0)) and not((lit_count_loc_load_load_fu_197_p1 = ap_const_lv32_1000)))) then 
                ap_phi_mux_tmpValue_1_phi_fu_109_p4 <= tmpValue_fu_205_p3;
            else 
                ap_phi_mux_tmpValue_1_phi_fu_109_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_tmpValue_1_phi_fu_109_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_predicate_op31_write_state4_assign_proc : process(icmp_ln51_reg_232, grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out)
    begin
                ap_predicate_op31_write_state4 <= (not((grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out = ap_const_lv32_0)) and (icmp_ln51_reg_232 = ap_const_lv1_0));
    end process;

    ap_ready <= internal_ap_ready;

    boosterStream_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, boosterStream_empty_n, icmp_ln51_fu_153_p2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (icmp_ln51_fu_153_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            boosterStream_blk_n <= boosterStream_empty_n;
        else 
            boosterStream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    boosterStream_read_assign_proc : process(ap_CS_fsm_state1, icmp_ln51_fu_153_p2, ap_block_state1, grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_boosterStream_read, ap_CS_fsm_state3)
    begin
        if (((icmp_ln51_fu_153_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            boosterStream_read <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            boosterStream_read <= grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_boosterStream_read;
        else 
            boosterStream_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_start <= grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_ap_start_reg;
    icmp_ln51_fu_153_p2 <= "1" when (input_size_dout = ap_const_lv32_0) else "0";

    input_size_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, input_size_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_size_blk_n <= input_size_empty_n;
        else 
            input_size_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_size_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, input_size_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_size_c_blk_n <= input_size_c_full_n;
        else 
            input_size_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_size_c_din <= input_size_dout;

    input_size_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            input_size_c_write <= ap_const_logic_1;
        else 
            input_size_c_write <= ap_const_logic_0;
        end if; 
    end process;


    input_size_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            input_size_read <= ap_const_logic_1;
        else 
            input_size_read <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state4, ap_block_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    lenOffset_Stream_blk_n_assign_proc : process(lenOffset_Stream_full_n, ap_CS_fsm_state4, icmp_ln51_reg_232, grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out)
    begin
        if ((not((grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out = ap_const_lv32_0)) and (icmp_ln51_reg_232 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            lenOffset_Stream_blk_n <= lenOffset_Stream_full_n;
        else 
            lenOffset_Stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lenOffset_Stream_din_assign_proc : process(ap_CS_fsm_state4, grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lenOffset_Stream_din, ap_phi_mux_tmpValue_1_phi_fu_109_p4, ap_predicate_op31_write_state4, ap_block_state4, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_predicate_op31_write_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_state4))) then 
            lenOffset_Stream_din <= ap_phi_mux_tmpValue_1_phi_fu_109_p4;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            lenOffset_Stream_din <= grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lenOffset_Stream_din;
        else 
            lenOffset_Stream_din <= grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lenOffset_Stream_din;
        end if; 
    end process;


    lenOffset_Stream_write_assign_proc : process(ap_CS_fsm_state4, grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lenOffset_Stream_write, ap_predicate_op31_write_state4, ap_block_state4, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_predicate_op31_write_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_state4))) then 
            lenOffset_Stream_write <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            lenOffset_Stream_write <= grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lenOffset_Stream_write;
        else 
            lenOffset_Stream_write <= ap_const_logic_0;
        end if; 
    end process;

    lit_count_loc_load_load_fu_197_p1 <= grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out;
    lit_outStream_din <= grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_outStream_din;
    lit_outStream_write <= grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_outStream_write;

    max_lit_limit_assign_proc : process(ap_CS_fsm_state4, icmp_ln51_reg_232, ap_block_state4, ap_phi_mux_lit_count_flag_1_phi_fu_130_p4, max_lit_limit_preg)
    begin
        if (((icmp_ln51_reg_232 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then 
            max_lit_limit <= ap_phi_mux_lit_count_flag_1_phi_fu_130_p4;
        else 
            max_lit_limit <= max_lit_limit_preg;
        end if; 
    end process;


    max_lit_limit_ap_vld_assign_proc : process(ap_CS_fsm_state4, icmp_ln51_reg_232, ap_block_state4)
    begin
        if (((icmp_ln51_reg_232 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then 
            max_lit_limit_ap_vld <= ap_const_logic_1;
        else 
            max_lit_limit_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_fu_159_p2 <= std_logic_vector(unsigned(input_size_4_reg_226) + unsigned(ap_const_lv32_FFFFFFFF));
    tmpValue_fu_205_p3 <= (grp_lz4CompressPart1_4096_1_Pipeline_lz4_divide_fu_138_lit_count_out & ap_const_lv32_0);
end behav;
